default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inventory_development
  username: postgres
  password: postgres
  host: db

test:
  <<: *default
  database: inventory_test
  username: postgres
  password: postgres
  host: db

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
